### ISSUE TITLE
Missing loops

### ISSUE THREAD

**Issue by ClickerMonkey** [MarcoWorms/learn.js#6]
Self explanatory: traditional for loop, for each property in object, for each element in an array, while, and do while.

**Comment by MarcoWorms** [comment]
Hey there! So, I purposely skipped this part since most of the operations achieved by loops can be achieved by map/filter/reduce and normally in a less mutable manner. I could link a reference on the end of the guide for whoever wants to learn more about the imperative way to write loops and their use-cases, do you have any content to recommend to be in that section? I trully have not found common use cases where is either for/while or it`s impossible to resolve, so that`s why I've skipped them, but i`ll be hapy to complement "what you didn't learn here" section with a good material about this.

**Comment by MarcoWorms** [comment]
I'd normally link something like MDN but the MDN page about `for` seems a bit scarce on info about the other modifiers that you mentioned https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for

**Comment by ClickerMonkey** [comment]
Common scenarios when map/filter/reduce don't make any sense or work:

- I need to iterate a known number of times (for)
- I need to iterate an unknown number of times (while/do)
- I need to iterate an unknown number of times - but at least once (do)
- I need to escape iteration (break)

There are contrived ways of doing the above with map/filter/reduce - but those methods are far less readable/maintainable/etc.

**Comment by MarcoWorms** [comment]
So, I didn't want to start an antagonist discussion on map VS for, but I think all scenarios listed do can be achieved by using a mix of functions and datatypes. 

* I need to iterate a known number of times (for i = ...)

```js
let result = Array.from({ length: i }).map((_, i) => {  })
```

* I need to iterate an unknown number of times (while/do)
recursion

* I need to iterate an unknown number of times - but at least once (do)
also recursion with an if

* I need to escape iteration (break)
also recursion with an if

I guess the larger take at least for me here is that I haven't talked about recursion in JS, thanks! I'll write a section on that

**Comment by ClickerMonkey** [comment]
What's the target audience of this repo? What kind of minimum knowledge about programming are you expecting them to have for the content to be applicable?

**Comment by MarcoWorms** [comment]
I don't think recursion is more difficult than loops or require different knowledge to be applicable so I don't understand why the target audience would matter for this question, but answering it anyways this repo is targeting anyone who wants to learn more about javascript be it a newbie or someone proeficient in other language, I think there are many places people can go for complete references (and they are linked on the end of the guide), most people are exposed to imperative programming in every channel they go to so I think there is no harm in avoiding imperative structures in this guide, sorry if this doesn't meet the expectations you had but like I commented in the first comment if you do have a good reference on for/whole loops I could add it on the end of the guide in the "what you didn't learn here", and I thank you for opening this discussion because now I'll add the recursion section which tackles the problem's you've listed and I hope to make it clear in the writing when it comes to production that recursion won't need any higher knowledge in order to achieve what for loops achieve.

**Comment by ClickerMonkey** [comment]
If your goal is to introduce anyone to the language - its' terrible that you're setting them down a horrible path. If you think `Array.from({ length: i })` is acceptable I'm concerned. If your goal is to teach people about functional JS - then name it that. Don't mislead people by teaching them the functional approach to everything when there are native ways to perform the logic that are more performant and easier to follow.

**Comment by MarcoWorms** [comment]
Well, like i said before sorry if your expectations for this repo were not met, there are plenty of other guides with other directions I hope you find one that resonates with you, thanks for your interaction because it did help me see there were some missing parts. We disagree about misleading people but that's ok. Cya!

**Comment by ClickerMonkey** [comment]
I don't need one that resonates with me - I just don't want to work with people in the future who think the above methods for solving a problem are appropriate. Anyone who is taking the position of an educator needs to be less "lets push my ways of doing things on other people" and communicate all ways that are available to solve a problem and when one is more applicable over others. I get this is simple and it's *yours* but the fact that some people may pick up bad habits from it is irresponsible. I don't think my expectation of "educational material should not mislead people" is unrealistic - it shouldn't be about my expectations it should be about the affects to the computer science field in general. 

Link to other articles all you want if you don't care for a particular approach, but clearly communicate your bias at the top of the README so the uneducated readers are aware of your predilections.

**Comment by MarcoWorms** [comment]
Well, since you want to follow up on this discussion I have no issues on keeping on!

`it shouldn't be about my expectations it should be about the affects to the computer science field in general.`

this is literally your expectation, you have just written it!.

I think you are giving a lot of merit to this guide if you are envisioning that people will read this and this will be their only source of information in the process of learning to getting a job. All the guides out there that explain imperative javascript does not start with the following warning: "this is an imperative js guide and it won't present you the functinoal way to do things", so I really don't think there is a need to add a disclaimer like that. This is simply an aggregation of concepts that one might say that are even not funcional since they don't enforce a type system and allows for mutations in many ways that the pure functional people would say it's not functional. So this is just a handfull of content on JavaScript, it's a huge tool and I understand that you do not share the same vision that I do on how to solve problems in the language! I don't think you are enjoying this discussion so there is no need to followup if you disagree with my view, this will never be the only and definitive JS guide so the case you described where you work only with people that think like me will never happen!

**Comment by ClickerMonkey** [comment]
Fair enough!
